# Generated by Django 2.2.16 on 2022-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220905_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'verbose_name': 'Единица Измерения', 'verbose_name_plural': 'Единицы Измерения'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'Корзина покупок'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag', verbose_name='Тэги'),
        ),
    ]
